---
title: "Solar Cycles and Radio Flux/ISN"
author: "David J Jackson"
date: "1/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```
 ```{r import data, echo=FALSE}
rm(list=ls())
kanzel <- data.table::fread("./kh_spots.csv")
kanzel$Ymd <- as.Date(kanzel$Ymd)
kanzel$Year <- year(kanzel$Ymd)
kanzel$Month <- month(kanzel$Ymd)
kanzel$Spots <- kanzel$s_n + kanzel$s_s
K1 <- kanzel %>% select(Ymd,Year,Month,R,Spots)
radio <- data.table::fread("./radio_flux.txt")
radio$Ymd <- as.Date(paste(radio$year, radio$month, radio$day, sep = "-"))
R1 <- radio %>% select(Ymd,year,month,f10.7)
```
```{r Calc 365 Day Moving Average, echo=FALSE}
K1 <- K1 %>% filter(Ymd >="1951-11-01")
K1$K365 <- forecast::ma(K1$R,order=365)
K1$KS365 <- forecast::ma(K1$Spots,order=365)
R1$R365 <- forecast::ma(R1$f10.7, order=365)
```

```{r Cycle 19, echo=FALSE}
K19 <- K1 %>% filter(Ymd >="1954-04-01" & Ymd<="1958-03-31")
R19 <- R1 %>% filter(Ymd >="1954-04-01" & Ymd<="1958-03-31")
```
```{r Cycle 20,echo=FALSE}
K20 <- K1 %>% filter(Ymd >="1964-10-01" & Ymd<="1968-11-30")
R20 <- R1 %>% filter(Ymd >="1964-10-01" & Ymd<="1968-11-30")
```
```{r Cycle 21,echo=FALSE}
K21 <- K1 %>% filter(Ymd >="1976-03-01" & Ymd<="1979-12-31")
R21 <- R1 %>% filter(Ymd >="1976-03-01" & Ymd<="1979-12-31")
```
```{r Cycle 22, echo=FALSE}
K22 <- K1 %>% filter(Ymd >="1986-09-01" & Ymd<="1989-11-30")
R22 <- R1 %>%filter(Ymd >="1986-09-01" & Ymd<="1989-11-30")
```
```{r Cucle 23, echo=FALSE}
K23 <- K1 %>% filter(Ymd >="1996-08-01" & Ymd<="2001-11-30")
R23 <- R1 %>% filter(Ymd >="1996-08-01" & Ymd<="2001-11-30")
```
```{r Cycle 24, echo=FALSE}
K24 <- K1 %>% filter(Ymd >="2008-12-01" & Ymd <="2014-04-30")
R24 <- R1 %>% filter(Ymd >="2008-12-01" & Ymd <="2014-04-30")
```
# Solar Cycle 19: Apr. 1954 - Mar. 1958

```{r Plot Cycle 19, echo=FALSE}
K19 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 19: Kranzel  ISN")
R19 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 19 Radio Flux: f10.7CM")

```
```{r Cycle 19 Moving Average,echo=FALSE}
ggplot() + geom_line(data=K19,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R19,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle("Cycle 19: ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```
\newpage

#  Solar Cycle 20: Oct. 1964 - Nov. 1988  

```{r Plot Cycle 20, echo=FALSE}
K20 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 20: Kranzel ISN")
R20 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 20 Radio Flux(f10.7CM)")

```
```{r Cycle 20 Moving Average,echo=FALSE}
ggplot() + geom_line(data=K20,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R20,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle(" Cycle 20: ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```
\newpage
# Solar Cycle 21: Mar. 1976 - Dec. 1979  

```{r Plot Cycle 21, echo=FALSE}
K21 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 21: Kranzel ISN")
R21 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 21 Radio Flux(f10.7CM)")

```
```{r Cycle 21 Movng Average,echo=FALSE}
ggplot() + geom_line(data=K21,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R21,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle("Cycle 21:ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```
\newpage
# Solar Cycle 22 : Sept. 1986 - NOv. 1989

```{r Plot Cycle 22, echo=FALSE}
K22 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 22: Kranzel ISN")
R22 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 22 Radio Flux(f10.7CM)")

```
```{r Cycle 22 Moving Average, echo=FALSE}
ggplot() + geom_line(data=K22,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R22,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle("Cycle 22: ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```
\newpage
# Solar Cycle 23: Aug. 1996 - Nov. 2001

```{r Plot Cycle 23, echo=FALSE}
K23 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 23: Kranzel ISN")
R23 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 23 Radio Flux(f10.7CM)")

```
```{r Cycle 23 Moving Average, echo=FALSE}
ggplot() + geom_line(data=K23,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R23,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle("Cycle 23: ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```
\newpage
# Solar Cycle 24: Dec.2008 - Apr. 2014

```{r Plot Cycle 24, echo=FALSE}
K24 %>% ggplot(aes(x=Ymd,y=R)) + geom_line() + geom_smooth() +
  ggtitle("Cycle 24: Kranzel ISN")
R24 %>% ggplot(aes(x=Ymd,y=f10.7)) + geom_line() + geom_smooth() +
  ggtitle(" Cycle 24 Radio Flux(f10.7CM)")

```
```{r Cycle 24 Moving Average, echo=FALSE}
ggplot() + geom_line(data=K24,aes(x=Ymd,y=K365,col="ISN")) + 
    geom_line(data=R24,aes(x=Ymd,y=R365,col="Flux")) + 
    ggtitle("Cycle 24: ISN/Radio Flux 365 Day Moving Average") + ylab("Moving Average")
```


 
 